//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.09 at 02:41:00 PM IST 
//


package com.vodacom.GenericCURGatewayMS.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for modifyAttributeRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="modifyAttributeRequest"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{java:net.voda.io}AdapterRequest"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{java:net.voda.curgw.io}CURAttributes"/&gt;
 *         &lt;element ref="{java:net.voda.curgw.io}queryString"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "modifyAttributeRequest", propOrder = {
    "curAttributes",
    "queryString"
})
public class ModifyAttributeRequest
    extends AdapterRequest
{

    @XmlElement(name = "CURAttributes", namespace = "java:net.voda.curgw.io", required = true)
    protected CURAttributes curAttributes;
    @XmlElement(namespace = "java:net.voda.curgw.io", required = true)
    protected String queryString;

    /**
     * Gets the value of the curAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link CURAttributes }
     *     
     */
    public CURAttributes getCURAttributes() {
        return curAttributes;
    }

    /**
     * Sets the value of the curAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link CURAttributes }
     *     
     */
    public void setCURAttributes(CURAttributes value) {
        this.curAttributes = value;
    }

    /**
     * Gets the value of the queryString property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQueryString() {
        return queryString;
    }

    /**
     * Sets the value of the queryString property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQueryString(String value) {
        this.queryString = value;
    }

}
