//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.09 at 02:41:00 PM IST 
//


package com.vodacom.GenericCURGatewayWS.domain;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CURAttributesResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CURAttributesResponse"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{java:net.voda.io}AdapterResponse"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="CURAttributes" type="{java:net.voda.curgw.io}CURAttributes" maxOccurs="unbounded" minOccurs="0" form="qualified"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CURAttributesResponse", namespace = "java:net.voda.curgw.io", propOrder = {
    "curAttributes"
})
public class CURAttributesResponse
    extends AdapterResponse
{

    @XmlElement(name = "CURAttributes", namespace = "java:net.voda.curgw.io")
    protected List<CURAttributes> curAttributes;

    /**
     * Gets the value of the curAttributes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the curAttributes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCURAttributes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CURAttributes }
     * 
     * 
     */
    public List<CURAttributes> getCURAttributes() {
        if (curAttributes == null) {
            curAttributes = new ArrayList<CURAttributes>();
        }
        return this.curAttributes;
    }

}
