//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.09 at 02:41:00 PM IST 
//


package com.vodacom.GenericCURGatewayWS.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for getCurAttributes complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="getCurAttributes"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="curAttributesRequest" type="{java:net.voda.curgw.io}CURAttributesRequest" minOccurs="0" form="qualified"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getCurAttributes", propOrder = {
    "curAttributesRequest"
})
public class GetCurAttributes {

    @XmlElement(namespace = "http://www.vodacom.co.za/")
    protected CURAttributesRequest curAttributesRequest;

    /**
     * Gets the value of the curAttributesRequest property.
     * 
     * @return
     *     possible object is
     *     {@link CURAttributesRequest }
     *     
     */
    public CURAttributesRequest getCurAttributesRequest() {
        return curAttributesRequest;
    }

    /**
     * Sets the value of the curAttributesRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link CURAttributesRequest }
     *     
     */
    public void setCurAttributesRequest(CURAttributesRequest value) {
        this.curAttributesRequest = value;
    }

}
