//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.09 at 02:41:00 PM IST 
//


package com.vodacom.GenericCURGatewayWS.domain;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the GenericCURGatewayWS.wsdl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CURAttributes_QNAME = new QName("java:net.voda.curgw.io", "CURAttributes");
    private final static QName _QueryString_QNAME = new QName("java:net.voda.curgw.io", "queryString");
    private final static QName _CURGatewaySystemException_QNAME = new QName("http://www.vodacom.co.za/", "CURGatewaySystemException");
    private final static QName _CreateCURObject_QNAME = new QName("http://www.vodacom.co.za/", "createCURObject");
    private final static QName _CreateCURObjectResponse_QNAME = new QName("http://www.vodacom.co.za/", "createCURObjectResponse");
    private final static QName _DeleteCURObject_QNAME = new QName("http://www.vodacom.co.za/", "deleteCURObject");
    private final static QName _DeleteCURObjectResponse_QNAME = new QName("http://www.vodacom.co.za/", "deleteCURObjectResponse");
    private final static QName _GetCurAttributes_QNAME = new QName("http://www.vodacom.co.za/", "getCurAttributes");
    private final static QName _GetCurAttributesResponse_QNAME = new QName("http://www.vodacom.co.za/", "getCurAttributesResponse");
    private final static QName _ModifyCURAttributes_QNAME = new QName("http://www.vodacom.co.za/", "modifyCURAttributes");
    private final static QName _ModifyCURAttributesResponse_QNAME = new QName("http://www.vodacom.co.za/", "modifyCURAttributesResponse");
    private final static QName _RefreshAllPools_QNAME = new QName("http://www.vodacom.co.za/", "refreshAllPools");
    private final static QName _RefreshAllPoolsResponse_QNAME = new QName("http://www.vodacom.co.za/", "refreshAllPoolsResponse");
    private final static QName _RefreshAuthPool_QNAME = new QName("http://www.vodacom.co.za/", "refreshAuthPool");
    private final static QName _RefreshAuthPoolResponse_QNAME = new QName("http://www.vodacom.co.za/", "refreshAuthPoolResponse");
    private final static QName _RefreshIdvPool_QNAME = new QName("http://www.vodacom.co.za/", "refreshIdvPool");
    private final static QName _RefreshIdvPoolResponse_QNAME = new QName("http://www.vodacom.co.za/", "refreshIdvPoolResponse");
    private final static QName _RefreshProfPool_QNAME = new QName("http://www.vodacom.co.za/", "refreshProfPool");
    private final static QName _RefreshProfPoolResponse_QNAME = new QName("http://www.vodacom.co.za/", "refreshProfPoolResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: GenericCURGatewayWS.wsdl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AdapterRequest }
     * 
     */
    public AdapterRequest createAdapterRequest() {
        return new AdapterRequest();
    }

    /**
     * Create an instance of {@link AdapterResponse }
     * 
     */
    public AdapterResponse createAdapterResponse() {
        return new AdapterResponse();
    }

    /**
     * Create an instance of {@link CURAttributes }
     * 
     */
    public CURAttributes createCURAttributes() {
        return new CURAttributes();
    }

    /**
     * Create an instance of {@link CURAttribute }
     * 
     */
    public CURAttribute createCURAttribute() {
        return new CURAttribute();
    }

    /**
     * Create an instance of {@link CURAttributesRequest }
     * 
     */
    public CURAttributesRequest createCURAttributesRequest() {
        return new CURAttributesRequest();
    }

    /**
     * Create an instance of {@link CURAttributesResponse }
     * 
     */
    public CURAttributesResponse createCURAttributesResponse() {
        return new CURAttributesResponse();
    }

    /**
     * Create an instance of {@link CURGatewaySystemException }
     * 
     */
    public CURGatewaySystemException createCURGatewaySystemException() {
        return new CURGatewaySystemException();
    }

    /**
     * Create an instance of {@link CreateCURObject }
     * 
     */
    public CreateCURObject createCreateCURObject() {
        return new CreateCURObject();
    }

    /**
     * Create an instance of {@link CreateCURObjectResponse }
     * 
     */
    public CreateCURObjectResponse createCreateCURObjectResponse() {
        return new CreateCURObjectResponse();
    }

    /**
     * Create an instance of {@link DeleteCURObject }
     * 
     */
    public DeleteCURObject createDeleteCURObject() {
        return new DeleteCURObject();
    }

    /**
     * Create an instance of {@link DeleteCURObjectResponse }
     * 
     */
    public DeleteCURObjectResponse createDeleteCURObjectResponse() {
        return new DeleteCURObjectResponse();
    }

    /**
     * Create an instance of {@link GetCurAttributes }
     * 
     */
    public GetCurAttributes createGetCurAttributes() {
        return new GetCurAttributes();
    }

    /**
     * Create an instance of {@link GetCurAttributesResponse }
     * 
     */
    public GetCurAttributesResponse createGetCurAttributesResponse() {
        return new GetCurAttributesResponse();
    }

    /**
     * Create an instance of {@link ModifyCURAttributes }
     * 
     */
    public ModifyCURAttributes createModifyCURAttributes() {
        return new ModifyCURAttributes();
    }

    /**
     * Create an instance of {@link ModifyCURAttributesResponse }
     * 
     */
    public ModifyCURAttributesResponse createModifyCURAttributesResponse() {
        return new ModifyCURAttributesResponse();
    }

    /**
     * Create an instance of {@link RefreshAllPools }
     * 
     */
    public RefreshAllPools createRefreshAllPools() {
        return new RefreshAllPools();
    }

    /**
     * Create an instance of {@link RefreshAllPoolsResponse }
     * 
     */
    public RefreshAllPoolsResponse createRefreshAllPoolsResponse() {
        return new RefreshAllPoolsResponse();
    }

    /**
     * Create an instance of {@link RefreshAuthPool }
     * 
     */
    public RefreshAuthPool createRefreshAuthPool() {
        return new RefreshAuthPool();
    }

    /**
     * Create an instance of {@link RefreshAuthPoolResponse }
     * 
     */
    public RefreshAuthPoolResponse createRefreshAuthPoolResponse() {
        return new RefreshAuthPoolResponse();
    }

    /**
     * Create an instance of {@link RefreshIdvPool }
     * 
     */
    public RefreshIdvPool createRefreshIdvPool() {
        return new RefreshIdvPool();
    }

    /**
     * Create an instance of {@link RefreshIdvPoolResponse }
     * 
     */
    public RefreshIdvPoolResponse createRefreshIdvPoolResponse() {
        return new RefreshIdvPoolResponse();
    }

    /**
     * Create an instance of {@link RefreshProfPool }
     * 
     */
    public RefreshProfPool createRefreshProfPool() {
        return new RefreshProfPool();
    }

    /**
     * Create an instance of {@link RefreshProfPoolResponse }
     * 
     */
    public RefreshProfPoolResponse createRefreshProfPoolResponse() {
        return new RefreshProfPoolResponse();
    }

    /**
     * Create an instance of {@link ModifyAttributeRequest }
     * 
     */
    public ModifyAttributeRequest createModifyAttributeRequest() {
        return new ModifyAttributeRequest();
    }

    /**
     * Create an instance of {@link ModifyAttributeResponse }
     * 
     */
    public ModifyAttributeResponse createModifyAttributeResponse() {
        return new ModifyAttributeResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CURAttributes }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "java:net.voda.curgw.io", name = "CURAttributes")
    public JAXBElement<CURAttributes> createCURAttributes(CURAttributes value) {
        return new JAXBElement<CURAttributes>(_CURAttributes_QNAME, CURAttributes.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "java:net.voda.curgw.io", name = "queryString")
    public JAXBElement<String> createQueryString(String value) {
        return new JAXBElement<String>(_QueryString_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CURGatewaySystemException }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.vodacom.co.za/", name = "CURGatewaySystemException")
    public JAXBElement<CURGatewaySystemException> createCURGatewaySystemException(CURGatewaySystemException value) {
        return new JAXBElement<CURGatewaySystemException>(_CURGatewaySystemException_QNAME, CURGatewaySystemException.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateCURObject }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.vodacom.co.za/", name = "createCURObject")
    public JAXBElement<CreateCURObject> createCreateCURObject(CreateCURObject value) {
        return new JAXBElement<CreateCURObject>(_CreateCURObject_QNAME, CreateCURObject.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateCURObjectResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.vodacom.co.za/", name = "createCURObjectResponse")
    public JAXBElement<CreateCURObjectResponse> createCreateCURObjectResponse(CreateCURObjectResponse value) {
        return new JAXBElement<CreateCURObjectResponse>(_CreateCURObjectResponse_QNAME, CreateCURObjectResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeleteCURObject }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.vodacom.co.za/", name = "deleteCURObject")
    public JAXBElement<DeleteCURObject> createDeleteCURObject(DeleteCURObject value) {
        return new JAXBElement<DeleteCURObject>(_DeleteCURObject_QNAME, DeleteCURObject.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeleteCURObjectResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.vodacom.co.za/", name = "deleteCURObjectResponse")
    public JAXBElement<DeleteCURObjectResponse> createDeleteCURObjectResponse(DeleteCURObjectResponse value) {
        return new JAXBElement<DeleteCURObjectResponse>(_DeleteCURObjectResponse_QNAME, DeleteCURObjectResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetCurAttributes }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.vodacom.co.za/", name = "getCurAttributes")
    public JAXBElement<GetCurAttributes> createGetCurAttributes(GetCurAttributes value) {
        return new JAXBElement<GetCurAttributes>(_GetCurAttributes_QNAME, GetCurAttributes.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetCurAttributesResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.vodacom.co.za/", name = "getCurAttributesResponse")
    public JAXBElement<GetCurAttributesResponse> createGetCurAttributesResponse(GetCurAttributesResponse value) {
        return new JAXBElement<GetCurAttributesResponse>(_GetCurAttributesResponse_QNAME, GetCurAttributesResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ModifyCURAttributes }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.vodacom.co.za/", name = "modifyCURAttributes")
    public JAXBElement<ModifyCURAttributes> createModifyCURAttributes(ModifyCURAttributes value) {
        return new JAXBElement<ModifyCURAttributes>(_ModifyCURAttributes_QNAME, ModifyCURAttributes.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ModifyCURAttributesResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.vodacom.co.za/", name = "modifyCURAttributesResponse")
    public JAXBElement<ModifyCURAttributesResponse> createModifyCURAttributesResponse(ModifyCURAttributesResponse value) {
        return new JAXBElement<ModifyCURAttributesResponse>(_ModifyCURAttributesResponse_QNAME, ModifyCURAttributesResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RefreshAllPools }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.vodacom.co.za/", name = "refreshAllPools")
    public JAXBElement<RefreshAllPools> createRefreshAllPools(RefreshAllPools value) {
        return new JAXBElement<RefreshAllPools>(_RefreshAllPools_QNAME, RefreshAllPools.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RefreshAllPoolsResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.vodacom.co.za/", name = "refreshAllPoolsResponse")
    public JAXBElement<RefreshAllPoolsResponse> createRefreshAllPoolsResponse(RefreshAllPoolsResponse value) {
        return new JAXBElement<RefreshAllPoolsResponse>(_RefreshAllPoolsResponse_QNAME, RefreshAllPoolsResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RefreshAuthPool }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.vodacom.co.za/", name = "refreshAuthPool")
    public JAXBElement<RefreshAuthPool> createRefreshAuthPool(RefreshAuthPool value) {
        return new JAXBElement<RefreshAuthPool>(_RefreshAuthPool_QNAME, RefreshAuthPool.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RefreshAuthPoolResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.vodacom.co.za/", name = "refreshAuthPoolResponse")
    public JAXBElement<RefreshAuthPoolResponse> createRefreshAuthPoolResponse(RefreshAuthPoolResponse value) {
        return new JAXBElement<RefreshAuthPoolResponse>(_RefreshAuthPoolResponse_QNAME, RefreshAuthPoolResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RefreshIdvPool }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.vodacom.co.za/", name = "refreshIdvPool")
    public JAXBElement<RefreshIdvPool> createRefreshIdvPool(RefreshIdvPool value) {
        return new JAXBElement<RefreshIdvPool>(_RefreshIdvPool_QNAME, RefreshIdvPool.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RefreshIdvPoolResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.vodacom.co.za/", name = "refreshIdvPoolResponse")
    public JAXBElement<RefreshIdvPoolResponse> createRefreshIdvPoolResponse(RefreshIdvPoolResponse value) {
        return new JAXBElement<RefreshIdvPoolResponse>(_RefreshIdvPoolResponse_QNAME, RefreshIdvPoolResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RefreshProfPool }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.vodacom.co.za/", name = "refreshProfPool")
    public JAXBElement<RefreshProfPool> createRefreshProfPool(RefreshProfPool value) {
        return new JAXBElement<RefreshProfPool>(_RefreshProfPool_QNAME, RefreshProfPool.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RefreshProfPoolResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.vodacom.co.za/", name = "refreshProfPoolResponse")
    public JAXBElement<RefreshProfPoolResponse> createRefreshProfPoolResponse(RefreshProfPoolResponse value) {
        return new JAXBElement<RefreshProfPoolResponse>(_RefreshProfPoolResponse_QNAME, RefreshProfPoolResponse.class, null, value);
    }

}
